// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechXpress_infrastructure.Data;

#nullable disable

namespace TechXpress_infrastructure.Migrations
{
    [DbContext(typeof(TechXpress_context))]
    [Migration("20250322055532_initiariasdaaa")]
    partial class initiariasdaaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechXpress_domain.Entities.ActiveSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrentSession")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActiveSessions");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ApplicationUserId1");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.CartItem", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.LoginHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrentSession")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistoryEntries");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<string>("LastFourDigits")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrackingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://th.bing.com/th/id/R.f9b7e4f64d30ecd7020860db1f89bb94?rik=CzEbAPGXFoZUZg&pid=ImgRaw&r=0",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.genesink.com/wp-content/uploads/2019/03/display-vignette.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://th.bing.com/th/id/R.714e4d18d0c3392a0b41d063f0ae9228?rik=br4ovv8sBZPdBQ&riu=http%3a%2f%2fwww.giaitech.com.cn%2fwp-content%2fuploads%2f20160217001710322.jpg&ehk=7lw9IURGFO1GTdD1fAioHSOXwVykGuxLIDXGYIAuN9s%3d&risl=&pid=ImgRaw&r=0",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://th.bing.com/th/id/OIP.RbXiEBlo0TjEwllefkKUngHaEK?rs=1&pid=ImgDetMain",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://sm.mashable.com/t/mashable_in/review/l/lenovo-yog/lenovo-yoga-c940-14-inch-review-a-powerful-laptop-that-adapt_698k.960.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://www.stuff.tv/wp-content/uploads/sites/2/2022/10/Lenovo-Yoga-Slim-9i-lead.jpg?w=1080",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://cdn.mos.cms.futurecdn.net/bP2RiEaSMDEkCV6jN7o4JM-1280-80.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://th.bing.com/th/id/OIP.7RoVQDUJu8-JmfPTyAuu1QHaE8?pid=ImgDet&w=474&h=316&rs=1",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://th.bing.com/th/id/OIP.Ny7wVnZcwlxAtVJio9W8agHaE8?pid=ImgDet&w=474&h=316&rs=1",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://th.bing.com/th/id/OIP.Bin9XqWpiw52DFAu4vK6ngHaHa?rs=1&pid=ImgDetMain",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://images5.tanganetwork.com/prod?bucket=tanga-fetched-images-prod&filename=5848e000-8105-11e7-b99a-ab8f21c63662.jpg&width=635&height=635&quality=90",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://th.bing.com/th/id/OIP.xNpbYvCqv6zVkycime3ZrQHaGy?w=655&h=600&rs=1&pid=ImgDetMain",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://a-static.mlcdn.com.br/1500x1500/smart-tv-55-crystal-4k-samsung-55au8000-wi-fi-bluetooth-hdr-alexa-built-in-3-hdmi-2-usb/magazineluiza/193441900/7fabc39533e941e2c669887a003e6a4f.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://th.bing.com/th/id/OIP.WgYZbwCh_7ILVpJTeAjaQQHaHP?w=2943&h=2879&rs=1&pid=ImgDetMain",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6401/6401738cv1d.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://th.bing.com/th/id/OIP.05qN8o496JUUFxEcno1DMgAAAA?rs=1&pid=ImgDetMain",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://th.bing.com/th/id/OIP.dfsGUIL7GLKPvs2_NfqRCQHaHa?w=710&h=710&rs=1&pid=ImgDetMain",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://c1.neweggimages.com/ProductImage/96-811-092-01.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://i5.walmartimages.com/asr/903ecb9c-b1f4-47ad-a8e6-02813adda405.a074dc6a0ebbb7580d2a9e7594e030ab.jpeg?odnWidth=612&odnHeight=612&odnBg=ffffff",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://ae01.alicdn.com/kf/HTB1HyPdgfNZWeJjSZFpq6xjBFXaw/ZEALOT-B19-HiFi-Bluetooth-Headphones-Foldable-Wireless-Stereo-Earphone-Headsets-with-Mic-Micro-SD-Card-Slot.jpg_640x640.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://ae01.alicdn.com/kf/HTB1RejuXmYTBKNjSZKbq6xJ8pXaE/B19-Bluetooth-Headphones-Wireless-Stereo-HiFi-Music-Headphone-with-Mic-Headsets-Micro-SD-Card-Slot-FM.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://cdn.vox-cdn.com/uploads/chorus_image/image/72828338/wh5g758d.0.png",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://gagadget.com/media/cache/83/7d/837dd2b7cfaab35157c0c4bfb7989e61.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://cdn.mos.cms.futurecdn.net/PynLBY7LkNLNQ4uu44xwjc.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://m.media-amazon.com/images/I/817NiRrxXUL.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://m.media-amazon.com/images/I/41Xf2i6uRGL._SL500_.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://media.diy.com/is/image/KingfisherDigital/kitchen-perfected-eco-friendly-blue-illuminating-cordless-glass-kettle-1-7ltr-2200w~5052337012572_01c_MP?$MOB_PREV$&$width=768&$height=768",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://th.bing.com/th/id/OIP.aQ_uIV3Q_-CE7YvDOaj1RgHaHa?rs=1&pid=ImgDetMain",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://ae01.alicdn.com/kf/HTB13dALPFXXXXcxXFXXq6xXFXXXa/Smart-Bracelet-Bracelets-Fitness-Tracker-Band-Wristband-Wearable-Devices-Watch-Pulsera-Inteligente-Pulse-Monitor-Pk-Xiomi.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "https://th.bing.com/th/id/OIP.k8ijMJxs-Kmr4-3hekQGlgHaHa?w=500&h=500&rs=1&pid=ImgDetMain",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "https://th.bing.com/th/id/OIP.PsDbUPIRgi5r3En0Wu_TLQAAAA?w=474&h=474&rs=1&pid=ImgDetMain",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "https://i0.wp.com/bestbargains.lk/wp-content/uploads/2021/01/maxmo-air-fryer-sri-lanka.jpg?w=720&ssl=1",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "https://totalrvandcamping.com.au/wp-content/uploads/2023/09/301485_1_0gai9yk11j6ymwf9-1024x1024.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "https://www.goodontop.com/images/foods/low-card-foods/speakers/tribit-ts-bts20-xsound-go-bluetooth-speaker-by-tribit.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "https://th.bing.com/th/id/OIP.F5x-7Dkp5YuOsJAw1V0NjAHaGS?w=1000&h=849&rs=1&pid=ImgDetMain",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 36,
                            ImageUrl = "https://robots.net/wp-content/uploads/2019/07/2_9_Tribit-XSound-Go-portable-Speakers.jpeg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 37,
                            ImageUrl = "https://th.bing.com/th/id/R.754d75dc6939872b63d7ae2be6dd27ac?rik=R%2bXH60jc2XXrCg&pid=ImgRaw&r=0",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 38,
                            ImageUrl = "https://th.bing.com/th/id/OIP.aT5wnR6ncddbkQ00gY0AIAHaFn?w=1350&h=1023&rs=1&pid=ImgDetMain",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 39,
                            ImageUrl = "https://th.bing.com/th/id/OIP.0QjMD0CM8JWA-xUEmBtYiwAAAA?w=474&h=474&rs=1&pid=ImgDetMain",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 40,
                            ImageUrl = "https://th.bing.com/th/id/R.8b855b77b3e79f9d969b4d3b563ec0e5?rik=F%2faC7BCXMYe9qw&pid=ImgRaw&r=0",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 41,
                            ImageUrl = "https://ae01.alicdn.com/kf/Hb804706445c749b5b98231b728f1fc79l/JONSBO-TW4-360-RGB-CPU-water-cooling-14-water-channels-Shenguang-synchronization-ARGB-controller-with-remote.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 42,
                            ImageUrl = "https://th.bing.com/th/id/OIP.CzBmj8oFONV0Ol7LS7sRqgHaDT?rs=1&pid=ImgDetMain",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 43,
                            ImageUrl = "https://whiteaways.lk/wp-content/uploads/2023/08/HIMA.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 44,
                            ImageUrl = "https://technicalustad.com/wp-content/uploads/2022/09/best-micro-atx-case-new-3-295x300.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 45,
                            ImageUrl = "https://s.alicdn.com/@sc04/kf/H16440c708e4d4dbf93018df44dfb5e3eS.png_300x300.png",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 46,
                            ImageUrl = "https://th.bing.com/th/id/OIP.1viVJI6lll5-tRlXvlCA-QHaHa?w=800&h=800&rs=1&pid=ImgDetMain",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 47,
                            ImageUrl = "https://www.makotekcomputers.com/cdn/shop/files/ASUS-ROG-STRIX-Z590-E-GAMING-WIFI-12-MONTHS-WARRANTY-MOTHERBOARD.png?v=1715388173",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 48,
                            ImageUrl = "https://th.bing.com/th/id/OIP.QMlbqRJ4WNyUxVjGZs5B1AHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 49,
                            ImageUrl = "https://th.bing.com/th/id/R.47ed04d9edb9483bb4578b82a7067ecf?rik=IvcOiG5amnNtmA&pid=ImgRaw&r=0",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 50,
                            ImageUrl = "https://gepig.com/news/4038.jpg",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 51,
                            ImageUrl = "https://th.bing.com/th/id/OIP.J524we_sLclBNYEOIGOppAAAAA?rs=1&pid=ImgDetMain",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 52,
                            ImageUrl = "https://th.bing.com/th/id/R.dd66a48254aca2d1e37b8887993a100c?rik=Ileg6QdLFs2iTA&pid=ImgRaw&r=0",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 53,
                            ImageUrl = "https://th.bing.com/th/id/OIP.zz1pXOlbd6blFLpXQoJdxgHaEY?w=900&h=533&rs=1&pid=ImgDetMain",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 54,
                            ImageUrl = "https://th.bing.com/th/id/OIP.YL2XY4-NUxdg4bo-AoTHfgHaD4?rs=1&pid=ImgDetMain",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 55,
                            ImageUrl = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6443/6443448_sd.jpg",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 56,
                            ImageUrl = "https://www.gsm-helmond.nl/wp-content/uploads/2021/09/ip13p.png",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 57,
                            ImageUrl = "https://th.bing.com/th/id/OIP.0BSb4aDNgwz98tWiSzghmAHaHa?pid=ImgDet&w=474&h=474&rs=1",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 58,
                            ImageUrl = "https://th.bing.com/th/id/R.a71e552fa9db627e970d4f9265b2bdea?rik=7c2q579igV01%2fw&riu=http%3a%2f%2f1.bp.blogspot.com%2f-8Sqoo-pIH44%2fVej65FF82dI%2fAAAAAAAAAMs%2fK1B1Jnijekk%2fs1600%2fbridge.jpg&ehk=Ri%2bfgoOprMK5WCr5iSwegmqi33uUKgYBsmYAwydbJIc%3d&risl=&pid=ImgRaw&r=0",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 59,
                            ImageUrl = "https://www.bdstall.com/asset/product-image/giant_15949.jpg",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 60,
                            ImageUrl = "https://i1.wp.com/www.itechnews.net/wp-content/uploads/2013/03/FujiFilm-FinePix-S8400W-44x-Long-Zoom-Camera-supports-WiFi-zooming-angle.jpg?fit=600%2C552",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 61,
                            ImageUrl = "https://th.bing.com/th/id/OIP.hO3M_lb6JnlfCzEfQad01wHaH0?rs=1&pid=ImgDetMain",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 62,
                            ImageUrl = "https://th.bing.com/th/id/OIP.ymSNRvHme27UC7q_gRxM9QHaJi?w=720&h=928&rs=1&pid=ImgDetMain",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 63,
                            ImageUrl = "https://i.ebayimg.com/images/g/UiYAAOSwz29kga0n/s-l1600.jpg",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 64,
                            ImageUrl = "https://th.bing.com/th/id/OIP.dUwz42xWONVV0_iixdxItAHaHa?w=646&h=646&rs=1&pid=ImgDetMain",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 65,
                            ImageUrl = "https://th.bing.com/th/id/OIP.JUprBEeYu8BSQviFHdwLXwHaIZ?w=679&h=770&rs=1&pid=ImgDetMain",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 66,
                            ImageUrl = "https://www.buyhomeappliance.co.uk/wp-content/uploads/2021/09/RF750N4ISF_3-scaled-1.jpg",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 67,
                            ImageUrl = "https://cdn.taw9eel.com/media/catalog/product/cache/1/image/519x/9df78eab33525d08d6e5fb8d27136e95/f/t/ftgc4565-en.jpg",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 68,
                            ImageUrl = "https://scene7.samsclub.com/is/image/samsclub/0071171957337_A",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 69,
                            ImageUrl = "https://cdn.media.amplience.net/i/xcite/545474-03?img404=default&w=2048&qlt=75&fmt=auto",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 70,
                            ImageUrl = "https://th.bing.com/th/id/R.831423052c67d6782e5c569149c22030?rik=TcoxTyim18pSxQ&pid=ImgRaw&r=0",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 71,
                            ImageUrl = "https://gh.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/60/0736041/1.jpg?2666",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 72,
                            ImageUrl = "https://m.media-amazon.com/images/I/51JdeBBTHKS._AC_SL1500_.jpg",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 73,
                            ImageUrl = "https://th.bing.com/th/id/OIP.hXrpTB9ISOzzr37bnsCR1AHaFC?rs=1&pid=ImgDetMain",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 74,
                            ImageUrl = "https://th.bing.com/th/id/OIP.nB_hHWbpe_jru29GCJ9mJQHaFK?rs=1&pid=ImgDetMain",
                            ProductId = 26
                        },
                        new
                        {
                            Id = 75,
                            ImageUrl = "https://www.pricerunner.dk/product/1200x630/3000665543/HP-Officejet-Pro-9013.jpg",
                            ProductId = 26
                        });
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EstimatedDelivery")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("bit");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("LanguagePreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfileImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProfileVisibility")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowBirthDate")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationUserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.WishlistItem", b =>
                {
                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.HasKey("WishlistId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechXpress_domain.Entities.ActiveSession", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Address", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ApplicationUserId1");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Cart", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Cart")
                        .HasForeignKey("TechXpress_domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.CartItem", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechXpress_domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.LoginHistoryEntry", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Order", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.OrderItem", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechXpress_domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Product", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.ProductImage", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Review", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Shipping", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.Order", "Order")
                        .WithOne("Shipping")
                        .HasForeignKey("TechXpress_domain.Entities.Shipping", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.UserProfile", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("TechXpress_domain.Entities.UserProfile", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Wishlist", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Wishlist")
                        .HasForeignKey("TechXpress_domain.Entities.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.WishlistItem", b =>
                {
                    b.HasOne("TechXpress_domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechXpress_domain.Entities.Product", null)
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId1");

                    b.HasOne("TechXpress_domain.Entities.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("Wishlist")
                        .IsRequired();
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Shipping")
                        .IsRequired();
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("TechXpress_domain.Entities.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
